In [1]:
import numpy as np

In [2]:
liste = [1,2,3,4,5]

In [3]:
np.array(liste)

array([1, 2, 3, 4, 5])

In [4]:
liste

[1, 2, 3, 4, 5]

In [5]:
arr = np.array(liste)

In [6]:
arr

array([1, 2, 3, 4, 5])

In [9]:
arr + 2

array([3, 4, 5, 6, 7])

In [10]:
arr * 2

array([ 2,  4,  6,  8, 10])

In [11]:
l = [1,2,3,'3']

In [13]:
arr2 = np.array(l)

In [19]:
type(arr2[0])

numpy.str_

In [20]:
arr2[0]

'1'

In [22]:
arr2[:2]

array(['1', '2'], 
      dtype='<U21')